### PR TITLE
Great package!

### PR DESCRIPTION
**Pull request by muschellij2**
This is a great package!  

I have added the nii2oro and namespace necessities for it to allow for the conversion between your nifti class and `oro.nifti`'s `nifti` class.  I know this may seem backwards comparatively as your package reads images quickly, but it wasn't on CRAN and I think addition would be great for those who commonly use `oro.nifti`.  

I love the comparison of NIfTI readers.  I may add that the  `ANTsR` package exists (only on GitHub, https://github.com/stnava/ANTsR).  It can be a bit of a hassle to install from source, but it also reads in NIfTI images and uses an C++ pointer, which may have similar read speeds (but fewer header accessor functions like `dumpNifti`.  If you don't want to go through the install, seems like your comparison still demonstrates a strong reason to use your implementation.

The big differences for `nii2oro` is the `datatype` and `bitpix` slots, which don't currently match when you read the same file:

```r
library(RNifti)
library(oro.nifti)
fname = system.file("extdata", "example.nii.gz", package = "RNifti")
image <- readNifti(fname)
img = oro.nifti::readNIfTI(fname, reorient = FALSE)
out = nii2oro(image)
all.equal(out, img)
```
```
[1] "Attributes: < Component “bitpix”: Mean relative difference: 0.5 >"   
[2] "Attributes: < Component “datatype”: Mean relative difference: 0.75 >"
[3] "Attributes: < Component “pixdim”: Mean absolute difference: 1 >"     
[4] "Attributes: < Component “regular”: 1 string mismatch >" 
```
and if we look at the `bitpix` and `datatype` from your package (in `out`) and `oro.nifti` (in `img`) we see the differences
```r
out@bitpix
```
```
[1] 64
```
```r
out@datatype
```
```
[1] 64
```
```r
img@datatype
```
```
[1] 16
```
```r
img@bitpix
```
```
[1] 32
```

Calling `FSL` from the `fslr` package, we see the result from FSL's `fslhd`:
```r
fslhd(fname)[c(1, 4, 15:17)]
```
```
[1] "filename       /Library/Frameworks/R.framework/Versions/3.3/Resources/library/RNifti/extdata/example.nii.gz"
[2] "data_type      FLOAT32"                                                                                     
[3] "datatype       16"                                                                                          
[4] "nbyper         4"                                                                                           
[5] "bitpix         32" 
```

### CODE REVIEW

**Comment by jonclayden** [comment]
Hi John, and thanks for the PR. There are several things to pick up on in your comment, so I'll take them one at a time.

- Thanks for letting me know about `ANTsR`. I'll try and get it installed and add it to the comparison.
- The `datatype` and `bitpix` mismatch is expected, but this could admittedly be better documented. If you call `dumpNifti(fname)` on the filename you will get what you expect; likewise if you call `dumpNifti(readNifti(fname,internal=TRUE))`. The reason is the difference between what `RNifti` calls an `internalImage`, which is just an external pointer to a C++ object and some basic metadata, and a `niftiImage`, which is an R array with a C++ object synchronised to it. Since R only has two numeric data types, `int` and `double`, the data type in the NIfTI data structure is changed to match.
- As for the PR itself, I'm loath to merge it because (a) minimal dependencies are important to me for this package, and importing `oro.nifti` also means a dependency cascade that includes `bitops` and `abind`; and (b) I think it's debatable that this conversion belongs in the `RNifti` package anyway. I handle conversion *from* `oro.nifti` objects already, and I think it makes more sense for each package to import to its own data structures, and then provide generic ways of accessing important parts of those data structures. Maybe it's worth asking Brandon what he thinks about adding the convertor to `oro.nifti` itself.

**Comment by muschellij2** [comment]
# Pull Request
WRT to the PR:
Understandable reasons about the integration to `oro.nifti`.  Let me know when it is on CRAN and I will integrate it with `oro.nifti`.

# Header changes
I agree with the `int` and `double` points about R, but I found it strange that if you read in an image and wrote it back out the header would change.  If you aren't using other software or don't care about changing headers, then please skip the next section.  I was just going over the behavior of `RNifti` and `oro.nifti`.  Both packages don't give exactly the same output binary files when writing.  Both will also give you and exact copy of the image if you wrote it to a file then read in that output file back into R.  The only thing I can see is that you have an "increase in precision" for `RNifti` in the header but not in `oro.nifti`.

## RNifti behavior
For example, I'd assume if you read in a NIfTI image, then wrote it back out you'd get the same header information:

```r
library(RNifti)
fname = system.file("extdata", "example.nii.gz", package = "RNifti")
image = readNifti(fname)
outfile =  tempfile(fileext = ".nii.gz")
writeNifti(image, file =outfile)
system(sprintf("diff %s %s", fname, outfile))
```
they differ, but are exactly the same when read back into R:
```r
image2 = readNifti(outfile)
all.equal(image, image2)
```
```
[1] TRUE
```
and the headers are not the same (as we've noted):
```r
library(fslr)
hd = fslhd(fname)
hd_out = fslhd(outfile)
df = data.frame(hd= hd, out= hd_out, stringsAsFactors = FALSE)
diff = df[ hd!= hd_out,]
diff = diff[ !grepl("filename", diff$hd),]
```
```
                            hd                         out
4       data_type      FLOAT32      data_type      FLOAT64
15           datatype       16           datatype       64
16            nbyper         4            nbyper         8
17           bitpix         32           bitpix         64
22 pixdim4        1.0000000000 pixdim4        0.0000000000
```

## oro.nifti behavior
The same behavior does occur, however in `oro.nifti` with respect to `diff`:
```r
library(oro.nifti)
fname = system.file("extdata", "example.nii.gz", package = "RNifti")
img = readNIfTI(fname)
outfile2 =  tempfile(fileext = "") #.nii.gz will be added
writeNIfTI(img, filename = outfile2)
outfile2 = paste0(outfile2, ".nii.gz")
system(sprintf("diff %s %s", fname, outfile2))
```
they differ, but when outfile2 is read in they are the same
```r
img2 = readNIfTI(outfile2)
all.equal(img, img2)
```
```
[1] TRUE
```
and the headers are the same
```r
library(fslr)
hd = fslhd(fname)
hd_out = fslhd(outfile2)
df = data.frame(hd= hd, out= hd_out, stringsAsFactors = FALSE)
diff = df[ hd!= hd_out,]
diff = diff[ !grepl("filename", diff$hd),]
```
```
[1] hd  out
<0 rows> (or 0-length row.names)
```

**Comment by jonclayden** [comment]
I absolutely care about interoperability, but binary diff isn't a reliable way of checking for "functionally equivalent" NIfTI-1 files, especially gzipped ones. For a start, there are elements of the binary format with only an informative value, such as the `description` field, which software tools will often set to identify the package that wrote the file. Secondly, `gzip` offers a number of different compression levels, each of which will produce a different binary file. (If you `gunzip` each file then the results from `oro.nifti` in your test are binary equivalent, at least on my system.)

In any case, as mentioned, whether the header is effectively modified by `RNifti` is under the control of the user. It happens by default, because otherwise if you read in an integer-valued image, added 0.1 to each voxel value and wrote it out again, the values would be truncated back to integers. I don't want the user to have to keep track of data types unless they are advanced enough to (a) care, and (b) know how to do better than the default in terms of space efficiency without data loss.

In the end, I'd suggest that compatibility between software through a standard file format is really about both keeping to the standard, and getting equivalent results when each reads files created by the other. As far as I know that's the case.

**Comment by jonclayden** [comment]
I added `ANTsR` to the performance comparison, by the way. As you expected, it performs very similarly to `RNifti`. It is quite heavy to install though!

**Comment by jonclayden** [comment]
Closing the PR without merging. Instead a note has been added to the documentation in commit 74d2828, clarifying the effect of the `internal` argument of `readNifti()` on the resulting image data type.

**Pull request closed without merging**
